### PR TITLE
Fix not focusing the selected value on menu open

### PR DESCRIPTION
**Pull request by Tirzono**
See: https://github.com/JedWatson/react-select/pull/3868

### CODE REVIEW

**Comment by marcelltoth** [comment]
Awesome. As this has been discussed in JedWatson#3868 no need to discuss it further here.

One thing before we can merge this is that we need to add a changeset. Could you add it please @Tirzono? Take a look at [here](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md) for the process, if you are not familiar.

IMO this is a patch bump for the `react-select-reborn` package.

**Comment by Tirzono** [comment]
I am not familiar with the process, but isn't it something that needs to be done on a release only and not when merging a single PR? Because there are many more things that have been merged to `master` since the last release, not only this PR.

Anyway, I'll have a closer look at it after the weekend, thank you for your reply.

**Comment by marcelltoth** [comment]
The release process is two steps.

This step needs to happen for every pull request, this just defines "what
your change is" (this part will go into the changelog upon release), and
"how severe your change is" (this will dictate which version number will
get bumped on release).

These will get written into a file in a ".changesets" folder, but nothing
else will happen.

When we decide to cut a release, the release tool will read these changeset
files, combine them into a changelog and bump the version number
accordingly.

**Comment by Tirzono** [comment]
I rebased my branch on your master and added a changeset.

**Comment by marcelltoth** [comment]
As contrary to their message, the original project is still dead, I'm continuing maintenance on this one.

Changeset looks perfect, thank you @Tirzono

**Pull request merged**
